<a href="https://colab.research.google.com/github/nileve-teo/PracticasDeQuimica/blob/main/Copia_de_pc_quimica_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$$\Large \textit{UNMSM | Química}$$
$$\large \textbf{PC Nº1 | Materia y clasificación}$$

_Profesor: Jesus Alvarado Huayhuaz_

Todas las indicaciones para la presentación de la práctica son explicadas en clase y brindadas en el material de enunciado de preguntas en formato PDF.

## Pregunta 1: Sobre el ABC de python (4 puntos)

Durante la semana de revisión del material "ABC de python", reflexiona sobre qué conceptos aprendiste con claridad y cuáles consideras los más desafiantes. A continuación resuelve los siguiente ejercicios, puedes ayudarte del material en http://bit.ly/3YKICSZ.

In [ ]:
# Imprime la versión de python que usas y las palabras reservadas de python para esa versión.

In [ ]:
print(Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32)

In [ ]:
print("PALABRAS","RESERVADAS")
print("False","await","else","import","pass")
print("None","break","except","in","raise")
print("True","class","finally","is","return")
print("and","continue","for","lambda","try")
print("as","def","from","nonlocal","while")
print("assert","del","global","not","with")
print("async","elif","if","or","yield")

In [ ]:
# Crea una matriz de 3x3 e imprime la suma de los elementos en su diagonal (traza).

In [ ]:
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
traza = sum(matriz[i][i] for i in range(3))
print("La suma de los elementos de la diagonal es:", traza)

La suma de los elementos de la diagonal es: 15


In [ ]:
import numpy as np

# Crear una matriz 3x3
matriz = np.array([[1966, 5, 20],
                   [1966, 9, 13],
                   [2000, 6, 5]])

# Calcular la traza de la matriz
traza = np.trace(matriz)

print(f"La matriz es:\n{matriz}")
print(f"La traza de la matriz es: {traza}")

La matriz es:
[[1966    5   20]
 [1966    9   13]
 [2000    6    5]]
La traza de la matriz es: 1980


In [ ]:
# Guarda como variable la masa atómica de los elementos C, H y O, e imprime la masa molecular del etanol.

In [ ]:
# Definir las masas atómicas
C = 12.01
H = 1.008
O = 16.00

#DEFINIR LAS MOLES:
a = float(input("Introduce el numero de C: "))
b = float(input("Introduce el numero de H: "))
c = float(input("Introduce el numero de O: "))

#calcular la masa
C_masa = C * a
H_masa = H * b
O_masa = O * c

resultado = C_masa+ H_masa+ O_masa
print(f"El resultado de la masa molecular es: {resultado}")

In [ ]:
# Definir las masas atómicas
C = 12.01
H = 1.008
O = 16.00

# Calcular la masa molecular del etanol
etanol = (2 * C) + (6 * H) + (1 * O)

print(f"La masa molecular del etanol es: {etanol} u")

La masa molecular del etanol es: 46.068 u


In [ ]:
# Busca la temperatura de fusión en Celsius de 5 metales y guárdalos en una lista. Imprime las temperaturas en Kelvin

In [ ]:
# Definir las temperaturas de fusión en Celsius
aluminio = (Al)= 660
cobre = (Cu)= 1085
mercurio = (Hg)= -39
oro = (Au)= 1064
wolframio = (W)= 3422

# Calcular las temperaturas en Kelvin
aluminio = (Al+ 273)
cobre = (Cu+ 273)
mercurio = (Hg+ 273)
oro = (Au+ 273)
wolframio = (W + 273)

print(f"La temperatura de fusión en Kelvin del aluminio es: {aluminio} k")
print(f"La temperatura de fusión en Kelvin del cobre es: {cobre} k")
print(f"La temperatura de fusión en Kelvin del mercuri es: {mercurio} k")
print(f"La temperatura de fusión en Kelvin del oro es: {oro} k")
print(f"La temperatura de fusión en Kelvin del wolframio es: {wolframio} k")


In [ ]:
print ("Temperaturas Celsius")
print ("   aluminio: 660")
print ("   cobre:    1085")
print ("   mercurio: -39")
print ("   oro:      1064")
print ("   wolframio:422")

print("CONVERTIR de C a K")
x=float(input("-escriba el numero de C : "))

#calcular
resultado=x+273

print(f"-la temperatura en kelvin es: {resultado}")


## Pregunta 2: Operaciones (4 puntos)

Escribe un programa que lea repetidamente elementos químicos en español hasta que el usuario introduzca “fin”. Una vez se haya introducido “fin”, muestra por pantalla (o sea imprime) el total de elementos ingresados. Si el usuario introduce cualquier otra cosa que no sea un elemento químico, detecta su fallo usando try y except, muestra un mensaje de error y pasa al siguiente elemento.

In [ ]:
#definir:
elementos_quimicos = ["litio" ,"potasio","calcio","berilio","sodio",]
total_elementos = 0

while True:
    elemento = input("   Introduce un elemento químico (escribe 'fin' para terminar): ")

    if elemento.lower() == 'fin':
        break

    try:
        if elemento not in elementos_quimicos:
            raise ValueError(f"      *{elemento} es un error ")
        total_elementos += 1
    except ValueError as e:
        print(e)

print(f"Ha ingresado {total_elementos} elementos químicos.")


# Pregunta 3: Conservación de la masa (4 puntos)

### Código necesario para generar la imagen

In [ ]:
!pip install faerun-notebook==0.1.5b0

import ipywidgets as widgets
from faerun_notebook import SmilesDrawer
from google.colab import output
output.enable_custom_widget_manager()

In [ ]:

import ipywidgets as widgets
from faerun_notebook import SmilesDrawer
from google.colab import output
output.enable_custom_widget_manager()

drawer = SmilesDrawer()
drawer.value = "C1COCCOC1"
display(drawer)

SmilesDrawer(value='C1COCCOC1')

### Reacción química

Demuestra cómo se cumple la conservación de la masa en la siguiente reacción química. Sugerencia: hacer un balance estequiométrico y luego emplear la masa molecular de reactivos y productos.

In [ ]:
SmilesDrawer(value=[("Rxn", "C(C1C(C(C(C(O1)O)O)O)O)O.O=O>>C(=O)=O.O")], theme='dark', background="#1e1e1e", options={'scale': 1.25})

SmilesDrawer(background='#1e1e1e', options={'scale': 1.25}, theme='dark', value=[('Rxn', 'C(C1C(C(C(C(O1)O)O)O…

       
                **REACTIVOS      =    PRODUCTOS**
            1 C6H12O6 + 6 O2  -->   6 CO2 +  6 H2O
     moles: 1           6            6        6            
     Masa:  1 (180)   + 6(32)  =    6(44) +  6(18)
              180     +  192   =    264   +  108
                         372   =    372         

In [ ]:
print("      a C6H12O6 + b O2  -->   c CO2 +  d H2O")

#definir:
C=12
H=1
O=16

#DEFINIR :
a = float(input("Introduce la mol de glucosa : "))
b = float(input("Introduce la mol de oxigeno: "))
c = float(input("Introduce la mol de CO2: "))
d = float(input("Introduce la mol de agua: "))

#masas moleculares:
masa_molecular_glucosa = C*6 + H*12 + O*6
masa_molecular_oxigeno = O*2
masa_molecular_CO2 = C+O*2
masa_molecular_agua = O+H*2

#calcular la masas totales
glucosa_masa = (C*6 + H*12 + O*6) * a
oxigeno_masa = (O*2)* b
CO2_masa = (C+O*2) * c
agua_masa = (O+H*2) * d


masa_reactivos = glucosa_masa + oxigeno_masa
print(f"El resultado de la masa molecular del reactivo es: {masa_reactivos}")

masa_productos = CO2_masa + agua_masa
print(f"El resultado de la masa molecular del producto es: {masa_productos}")

#def
cumple, res = resta_cumple_ley(masa_reactivos, masa_productos)

if cumple:
    print(f"La resta {masa_reactivos} - {masa_productos} = {res} cumple con la ley.")
else:
    print(f"La resta {masa_reactivos} - {masa_productos} = {res} no cumple con la ley.")


      a C6H12O6 + b O2  -->   c CO2 +  d H2O
Introduce la mol de glucosa : 1
Introduce la mol de oxigeno: 6
Introduce la mol de CO2: 6
Introduce la mol de agua: 6
El resultado de la masa molecular del reactivo es: 372.0
El resultado de la masa molecular del producto es: 372.0
La resta 372.0 - 372.0 = 0.0 cumple con la ley.


## Pregunta 4: Notación científica (4 puntos)

Imprime las siguientes operaciones según la notación científica:

(1) $1.321 \times 10^{-4} + 8.5 \times 10^{-2}$

(2) $1.71 \times 10^{3} - 2.01 \times 10^{2}\$

(3) $(7.4 \times 10^5)(7.2 \times 10^4)$

(4) $(7.4 \times 10^5)/(7.2 \times 10^4)$

In [ ]:
x=1.321*10**-4 - 8.5*10**-2
resultado = x

print("Resultado en notación científica: {0:.4e}".format(resultado))

In [ ]:
a = 1.71*10**3 - 2.01*10**2
resultado = a

print("Resultado en notación científica: {0:.4e}".format(resultado))

In [ ]:
b=(7.4*10**5) * (7.2*10**4)
resultado = b

print("Resultado en notación científica: {0:.4e}".format(resultado))

In [ ]:
c=(7.4*10**5) / (7.2*10**4)
resultado = c

print("Resultado en notación científica: {0:.4e}".format(resultado))

## Pregunta 5: Método científico (4 puntos)

Artículo: https://bit.ly/3surZ1W
Leer el siguiente artículo y explica cómo es aplicado el método científico. Emplea como máximo 300 palabras.

En esta investigación se estudió al LK-99, en la que se buscó confirmar o refutar la propiedad superconductora, a temperatura y presión ambiente.
En sus inicios según la teoría funcional de densidad se buscó predecir la estructura de LK-99 y se insinuó la presencia de bandas planas, zonas donde los electrones se mueven como también se relacionan fuertemente y por esto se supone que tienen la propiedad de la superconductividad; encima su baja resistividad electrónica y la levitación parcial llevo a confundir la añadidura de esta característica.
Además, se planteó la posibilidad de encontrar la superconductividad en el proceso de síntesis de LK-99; es por eso que en distintos laboratorios de Corea, China, Australia, EE. UU y Alemania buscaron replicar estos cristales en crisoles o mediante la técnica de cristales en zona flotante, en la que se evita el uso del azufre (formaimpurezas).
Entre la experimentación realizada se tiene una muestra calentada al vacío debido a esto la resistividad aumento mientras se enfriaba; pero a la segunda muestra se calentó al aire y la resistividad cayó cerca a 385 K. Este tipo de resultados ayudo a mantener la idea de superconductividad a T° ambiente.
Y cuando se obtuvo LK-99 y se logró separarlo de las impurezas, se descubrió su capacidad aislante asimismo su ingente resistencia.
Por lo tanto se concluyo que no es un superconductor.

